-- Amazon.eg recommended ScraperSearches (all DISABLED)
-- Safe to re-run: skips names that already exist.
-- Defaults: amazon_search / eg / ar-EG / featured / EGP / Cairo / 900s

SET NOCOUNT ON;

DECLARE @CreatedAt datetime2 = SYSUTCDATETIME();

;WITH Src AS (
    SELECT * FROM (VALUES
    -- ===== Large appliances: AC (min 2000) =====
    (N'AC Samsung', N'Samsung تكييف', CAST(2000 AS decimal(18,2))),
    (N'AC LG', N'LG تكييف', 2000),
    (N'AC Toshiba', N'Toshiba تكييف', 2000),
    (N'AC Sharp', N'Sharp تكييف', 2000),
    (N'AC Carrier', N'Carrier تكييف', 2000),
    (N'AC Fresh', N'Fresh تكييف', 2000),
    (N'AC Unionaire', N'Unionaire تكييف', 2000),
    (N'AC Tornado', N'Tornado تكييف', 2000),
    (N'AC Zanussi', N'Zanussi تكييف', 2000),
    (N'AC Hisense', N'Hisense تكييف', 2000),
    (N'AC Midea', N'Midea تكييف', 2000),
    (N'AC Gree', N'Gree تكييف', 2000),
    (N'AC Daikin', N'Daikin تكييف', 2000),
    (N'AC Media', N'ميديا تكييف', 2000),

    -- ===== Refrigerators (min 3000) =====
    (N'Fridge Samsung', N'Samsung ثلاجة', 3000),
    (N'Fridge LG', N'LG ثلاجة', 3000),
    (N'Fridge Toshiba', N'Toshiba ثلاجة', 3000),
    (N'Fridge Sharp', N'Sharp ثلاجة', 3000),
    (N'Fridge Zanussi', N'Zanussi ثلاجة', 3000),
    (N'Fridge Beko', N'Beko ثلاجة', 3000),
    (N'Fridge Fresh', N'Fresh ثلاجة', 3000),
    (N'Fridge Unionaire', N'Unionaire ثلاجة', 3000),
    (N'Fridge Tornado', N'Tornado ثلاجة', 3000),
    (N'Fridge Hisense', N'Hisense ثلاجة', 3000),
    (N'Fridge Electrolux', N'Electrolux ثلاجة', 3000),
    (N'Fridge Bosch', N'Bosch ثلاجة', 3000),
    (N'Fridge Indesit', N'Indesit ثلاجة', 3000),
    (N'Fridge Ariston', N'Ariston ثلاجة', 3000),
    (N'Fridge Whirlpool', N'Whirlpool ثلاجة', 3000),

    -- ===== Freezers (min 2000) =====
    (N'Freezer Toshiba', N'Toshiba فريزر', 2000),
    (N'Freezer Sharp', N'Sharp فريزر', 2000),
    (N'Freezer Zanussi', N'Zanussi فريزر', 2000),
    (N'Freezer Beko', N'Beko فريزر', 2000),
    (N'Freezer Fresh', N'Fresh فريزر', 2000),
    (N'Freezer Unionaire', N'Unionaire فريزر', 2000),
    (N'Freezer Tornado', N'Tornado فريزر', 2000),
    (N'Freezer Hisense', N'Hisense فريزر', 2000),
    (N'Freezer Samsung', N'Samsung فريزر', 2000),
    (N'Freezer LG', N'LG فريزر', 2000),

    -- ===== Washing machines (min 2500) =====
    (N'Washer Samsung', N'Samsung غسالة', 2500),
    (N'Washer LG', N'LG غسالة', 2500),
    (N'Washer Toshiba', N'Toshiba غسالة', 2500),
    (N'Washer Sharp', N'Sharp غسالة', 2500),
    (N'Washer Zanussi', N'Zanussi غسالة', 2500),
    (N'Washer Beko', N'Beko غسالة', 2500),
    (N'Washer Fresh', N'Fresh غسالة', 2500),
    (N'Washer Unionaire', N'Unionaire غسالة', 2500),
    (N'Washer Tornado', N'Tornado غسالة', 2500),
    (N'Washer Indesit', N'Indesit غسالة', 2500),
    (N'Washer Ariston', N'Ariston غسالة', 2500),
    (N'Washer Bosch', N'Bosch غسالة', 2500),
    (N'Washer Hoover', N'Hoover غسالة', 2500),
    (N'Washer Whirlpool', N'Whirlpool غسالة', 2500),

    -- ===== Washer dryers (min 4000) =====
    (N'Washer dryer Samsung', N'Samsung غسالة مجفف', 4000),
    (N'Washer dryer LG', N'LG غسالة مجفف', 4000),
    (N'Washer dryer Bosch', N'Bosch غسالة مجفف', 4000),
    (N'Washer dryer Beko', N'Beko غسالة مجفف', 4000),
    (N'Washer dryer Zanussi', N'Zanussi غسالة مجفف', 4000),
    (N'Washer dryer Toshiba', N'Toshiba غسالة مجفف', 4000),

    -- ===== Dryers (min 3000) =====
    (N'Dryer Samsung', N'Samsung مجفف', 3000),
    (N'Dryer LG', N'LG مجفف', 3000),
    (N'Dryer Bosch', N'Bosch مجفف', 3000),
    (N'Dryer Beko', N'Beko مجفف', 3000),
    (N'Dryer Zanussi', N'Zanussi مجفف', 3000),
    (N'Dryer Hoover', N'Hoover مجفف', 3000),

    -- ===== Dishwashers (min 3500) =====
    (N'Dishwasher Bosch', N'Bosch غسالة أطباق', 3500),
    (N'Dishwasher Beko', N'Beko غسالة أطباق', 3500),
    (N'Dishwasher Zanussi', N'Zanussi غسالة أطباق', 3500),
    (N'Dishwasher Siemens', N'Siemens غسالة أطباق', 3500),
    (N'Dishwasher Indesit', N'Indesit غسالة أطباق', 3500),
    (N'Dishwasher Ariston', N'Ariston غسالة أطباق', 3500),
    (N'Dishwasher Whirlpool', N'Whirlpool غسالة أطباق', 3500),
    (N'Dishwasher Sharp', N'Sharp غسالة أطباق', 3500),
    (N'Dishwasher Samsung', N'Samsung غسالة أطباق', 3500),
    (N'Dishwasher LG', N'LG غسالة أطباق', 3500),

    -- ===== Ovens / cookers / cooktops / hoods =====
    (N'Oven Bosch', N'Bosch فرن', 3000),
    (N'Oven Zanussi', N'Zanussi فرن', 2500),
    (N'Oven Beko', N'Beko فرن', 2500),
    (N'Oven Sharp', N'Sharp فرن', 2000),
    (N'Oven Fresh', N'Fresh فرن', 2000),
    (N'Oven Unionaire', N'Unionaire فرن', 2000),
    (N'Oven Ariston', N'Ariston فرن', 2500),
    (N'Oven Indesit', N'Indesit فرن', 2000),
    (N'Cooker Fresh', N'Fresh بوتاجاز', 2000),
    (N'Cooker Unionaire', N'Unionaire بوتاجاز', 2000),
    (N'Cooker Zanussi', N'Zanussi بوتاجاز', 2500),
    (N'Cooker Beko', N'Beko بوتاجاز', 2500),
    (N'Cooker Sharp', N'Sharp بوتاجاز', 2000),
    (N'Cooktop Bosch', N'Bosch سطح غاز', 2000),
    (N'Cooktop Zanussi', N'Zanussi سطح غاز', 1500),
    (N'Cooktop Beko', N'Beko سطح غاز', 1500),
    (N'Electric cooktop Bosch', N'Bosch سطح كهرباء', 2000),
    (N'Hood Bosch', N'Bosch شفاط', 1500),
    (N'Hood Fresh', N'Fresh شفاط', 1000),
    (N'Hood Unionaire', N'Unionaire شفاط', 1000),
    (N'Hood Zanussi', N'Zanussi شفاط', 1200),
    (N'Hood Beko', N'Beko شفاط', 1200),

    -- ===== Water heaters (min 1000) =====
    (N'Water heater Fresh', N'Fresh سخان', 1000),
    (N'Water heater Unionaire', N'Unionaire سخان', 1000),
    (N'Water heater Zanussi', N'Zanussi سخان', 1000),
    (N'Water heater Ariston', N'Ariston سخان', 1000),
    (N'Water heater Bosch', N'Bosch سخان', 1000),
    (N'Water heater Tornado', N'Tornado سخان', 1000),
    (N'Water heater Olympic', N'Olympic سخان', 1000),
    (N'Water heater Power', N'Power سخان', 1000),

    -- ===== Kitchen appliances =====
    (N'Air fryer Philips', N'Philips قلاية هوائية', 500),
    (N'Air fryer Tefal', N'Tefal قلاية هوائية', 500),
    (N'Air fryer Kenwood', N'Kenwood قلاية هوائية', 500),
    (N'Air fryer Black+Decker', N'Black Decker قلاية هوائية', 400),
    (N'Air fryer Tornado', N'Tornado قلاية هوائية', 400),
    (N'Air fryer Sokany', N'Sokany قلاية هوائية', 300),
    (N'Coffee DeLonghi', N'DeLonghi قهوة', 800),
    (N'Coffee Philips', N'Philips قهوة', 500),
    (N'Coffee Kenwood', N'Kenwood قهوة', 500),
    (N'Espresso DeLonghi', N'DeLonghi اسبريسو', 1000),
    (N'Nespresso', N'Nespresso', 500),
    (N'Blender Moulinex', N'Moulinex خلاط', 200),
    (N'Blender Braun', N'Braun خلاط', 250),
    (N'Blender Kenwood', N'Kenwood خلاط', 250),
    (N'Blender Philips', N'Philips خلاط', 250),
    (N'Blender Tefal', N'Tefal خلاط', 200),
    (N'Food processor Moulinex', N'Moulinex محضرة طعام', 300),
    (N'Food processor Kenwood', N'Kenwood محضرة طعام', 400),
    (N'Food processor Braun', N'Braun محضرة طعام', 400),
    (N'Stand mixer KitchenAid', N'KitchenAid عجان', 2000),
    (N'Stand mixer Kenwood', N'Kenwood عجان', 800),
    (N'Stand mixer Moulinex', N'Moulinex عجان', 500),
    (N'Juicer Moulinex', N'Moulinex عصارة', 200),
    (N'Juicer Philips', N'Philips عصارة', 250),
    (N'Juicer Braun', N'Braun عصارة', 250),
    (N'Meat grinder Moulinex', N'Moulinex مفرمة', 300),
    (N'Meat grinder Kenwood', N'Kenwood مفرمة', 400),
    (N'Meat grinder Bosch', N'Bosch مفرمة', 500),
    (N'Kettle Tefal', N'Tefal غلاية', 150),
    (N'Kettle Philips', N'Philips غلاية', 150),
    (N'Kettle Kenwood', N'Kenwood غلاية', 150),
    (N'Toaster Tefal', N'Tefal توستر', 150),
    (N'Toaster Philips', N'Philips توستر', 150),
    (N'Sandwich maker Tefal', N'Tefal صانديتش', 150),
    (N'Sandwich maker Moulinex', N'Moulinex صانديتش', 150),
    (N'Waffle maker Tefal', N'Tefal وافل', 200),
    (N'Rice cooker Tefal', N'Tefal طنجرة أرز', 200),
    (N'Rice cooker Philips', N'Philips أرز', 200),
    (N'Multicooker Tefal', N'Tefal قدر متعدد', 400),
    (N'Pressure cooker Tefal', N'Tefal حلة ضغط', 300),
    (N'Slow cooker Tefal', N'Tefal طهي بطيء', 300),
    (N'Ice cream maker', N'صانعة آيس كريم', 300),
    (N'Water dispenser Fresh', N'Fresh مبرد مياه', 800),
    (N'Water dispenser Tornado', N'Tornado مبرد مياه', 800),
    (N'Water dispenser Unionaire', N'Unionaire مبرد مياه', 800),
    (N'Microwave Samsung', N'Samsung ميكروويف', 800),
    (N'Microwave LG', N'LG ميكروويف', 800),
    (N'Microwave Sharp', N'Sharp ميكروويف', 700),
    (N'Microwave Toshiba', N'Toshiba ميكروويف', 700),
    (N'Microwave Fresh', N'Fresh ميكروويف', 600),
    (N'Microwave Tornado', N'Tornado ميكروويف', 600),
    (N'Mini oven Fresh', N'Fresh فرن كهرباء', 500),
    (N'Mini oven Tornado', N'Tornado فرن كهرباء', 500),
    (N'Mini oven Black+Decker', N'Black Decker فرن', 500),
    (N'Electric grill Tefal', N'Tefal شواية', 300),
    (N'Electric grill Philips', N'Philips شواية', 300),

    -- ===== Cookware / kitchen tools =====
    (N'Cookware Tefal', N'Tefal أطقم حلل', 200),
    (N'Cookware Prestige', N'Prestige حلل', 200),
    (N'Nonstick Tefal', N'Tefal غير لاصق', 150),
    (N'Stainless cookware', N'حلة استانلس', 200),
    (N'Knife set', N'طقم سكاكين', 100),
    (N'Dinnerware set', N'طقم عشاء', 150),
    (N'Plate set', N'طقم أطباق', 100),
    (N'Glassware set', N'طقم أكواب زجاج', 100),
    (N'Cutlery set', N'طقم معالق', 100),
    (N'Bakeware', N'صواني خبز', 100),
    (N'Food storage', N'حافظات طعام', 80),
    (N'Lunch box', N'لانش بوكس', 50),
    (N'Vacuum container', N'علبة تفريغ هواء', 100),

    -- ===== Home =====
    (N'Vacuum Samsung', N'Samsung مكنسة', 500),
    (N'Vacuum LG', N'LG مكنسة', 500),
    (N'Vacuum Philips', N'Philips مكنسة', 400),
    (N'Vacuum Bosch', N'Bosch مكنسة', 600),
    (N'Vacuum Black+Decker', N'Black Decker مكنسة', 300),
    (N'Vacuum Tornado', N'Tornado مكنسة', 300),
    (N'Vacuum Xiaomi', N'Xiaomi مكنسة', 500),
    (N'Robot vacuum Xiaomi', N'Xiaomi روبوت مكنسة', 1500),
    (N'Robot vacuum Samsung', N'Samsung روبوت مكنسة', 2000),
    (N'Robot vacuum Ecovacs', N'Ecovacs', 1500),
    (N'Steam cleaner', N'منظف بخار', 300),
    (N'Carpet cleaner', N'غسيل سجاد', 400),
    (N'Air purifier Xiaomi', N'Xiaomi منقي هواء', 500),
    (N'Air purifier Philips', N'Philips منقي هواء', 800),
    (N'Humidifier', N'مرطب هواء', 200),
    (N'Dehumidifier', N'مزيل رطوبة', 500),
    (N'Fan Fresh', N'Fresh مروحة', 200),
    (N'Fan Tornado', N'Tornado مروحة', 200),
    (N'Fan Unionaire', N'Unionaire مروحة', 200),
    (N'Heater Fresh', N'Fresh دفاية', 200),
    (N'Heater Tornado', N'Tornado دفاية', 200),
    (N'Smart home Xiaomi', N'Xiaomi smart home', 150),
    (N'Security camera Xiaomi', N'Xiaomi كاميرا مراقبة', 200),
    (N'Security camera TP-Link', N'TP-Link كاميرا', 250),
    (N'Doorbell', N'جرس باب فيديو', 300),

    -- ===== Electronics =====
    (N'iPhone', N'Apple iPhone', 5000),
    (N'Samsung Galaxy', N'Samsung Galaxy', 2000),
    (N'Xiaomi phone', N'Xiaomi', 1500),
    (N'Oppo', N'Oppo', 1500),
    (N'Realme', N'Realme', 1200),
    (N'Huawei phone', N'Huawei', 2000),
    (N'Nokia', N'Nokia', 800),
    (N'iPad', N'Apple iPad', 4000),
    (N'Samsung Tab', N'Samsung Galaxy Tab', 2000),
    (N'Lenovo Tab', N'Lenovo Tab', 1500),
    (N'MacBook', N'Apple MacBook', 15000),
    (N'Laptop Dell', N'Dell laptop', 5000),
    (N'Laptop HP', N'HP laptop', 5000),
    (N'Laptop Lenovo', N'Lenovo laptop', 5000),
    (N'Laptop ASUS', N'ASUS laptop', 5000),
    (N'Laptop Acer', N'Acer laptop', 4000),
    (N'Gaming laptop ASUS', N'ASUS ROG', 10000),
    (N'Gaming laptop MSI', N'MSI laptop', 10000),
    (N'Gaming laptop Lenovo', N'Lenovo Legion', 10000),
    (N'Desktop Dell', N'Dell desktop', 4000),
    (N'Desktop HP', N'HP desktop', 4000),
    (N'Monitor Samsung', N'Samsung monitor', 1500),
    (N'Monitor LG', N'LG monitor', 1500),
    (N'Monitor Dell', N'Dell monitor', 1500),
    (N'Monitor ASUS', N'ASUS monitor', 1500),
    (N'SSD Samsung', N'Samsung SSD', 300),
    (N'SSD WD', N'WD SSD', 250),
    (N'SSD Kingston', N'Kingston SSD', 200),
    (N'HDD Seagate', N'Seagate', 200),
    (N'HDD WD', N'WD hard disk', 200),
    (N'Router TP-Link', N'TP-Link راوتر', 200),
    (N'Router Huawei', N'Huawei راوتر', 200),
    (N'Mesh TP-Link', N'TP-Link Deco', 800),
    (N'Mesh Xiaomi', N'Xiaomi mesh', 600),
    (N'Printer HP', N'HP طابعة', 500),
    (N'Printer Epson', N'Epson طابعة', 500),
    (N'Printer Canon', N'Canon طابعة', 500),

    -- ===== Audio =====
    (N'AirPods', N'Apple AirPods', 1000),
    (N'Galaxy Buds', N'Samsung Galaxy Buds', 500),
    (N'Sony headphones', N'Sony headphones', 800),
    (N'Sony earbuds', N'Sony earbuds', 500),
    (N'JBL earbuds', N'JBL earbuds', 300),
    (N'JBL headphones', N'JBL headphones', 400),
    (N'JBL speaker', N'JBL speaker', 300),
    (N'Anker soundcore', N'Anker Soundcore', 200),
    (N'Bose', N'Bose', 1500),
    (N'Beats', N'Beats', 800),
    (N'Gaming headset Logitech', N'Logitech headset', 400),
    (N'Gaming headset Razer', N'Razer headset', 500),
    (N'Soundbar Samsung', N'Samsung soundbar', 1000),
    (N'Soundbar LG', N'LG soundbar', 1000),
    (N'Soundbar Sony', N'Sony soundbar', 1200),
    (N'Home theater', N'مسرح منزلي', 1000),

    -- ===== Entertainment =====
    (N'TV Samsung', N'Samsung تلفزيون', 3000),
    (N'TV LG', N'LG تلفزيون', 3000),
    (N'TV Toshiba', N'Toshiba تلفزيون', 2500),
    (N'TV Sharp', N'Sharp تلفزيون', 2500),
    (N'TV Hisense', N'Hisense تلفزيون', 2500),
    (N'TV TCL', N'TCL تلفزيون', 2500),
    (N'TV Sony', N'Sony تلفزيون', 4000),
    (N'OLED LG', N'LG OLED', 8000),
    (N'OLED Samsung', N'Samsung OLED', 8000),
    (N'QLED Samsung', N'Samsung QLED', 5000),
    (N'Projector', N'بروجكتور', 1000),
    (N'Fire TV', N'Fire TV', 500),
    (N'Android TV box', N'Android TV box', 300),

    -- ===== Gaming =====
    (N'PlayStation 5', N'PlayStation 5', 8000),
    (N'PS5', N'PS5', 8000),
    (N'PlayStation 4', N'PlayStation 4', 3000),
    (N'Xbox Series', N'Xbox Series', 6000),
    (N'Xbox', N'Xbox', 4000),
    (N'Nintendo Switch', N'Nintendo Switch', 4000),
    (N'DualSense', N'DualSense', 800),
    (N'Xbox controller', N'Xbox controller', 600),
    (N'Gaming chair', N'كرسي ألعاب', 1000),
    (N'Gaming monitor', N'شاشة ألعاب', 2000),
    (N'Gaming mouse Logitech', N'Logitech G mouse', 200),
    (N'Gaming mouse Razer', N'Razer mouse', 250),
    (N'Gaming keyboard', N'كيبورد ألعاب', 300),

    -- ===== Wearables =====
    (N'Apple Watch', N'Apple Watch', 3000),
    (N'Galaxy Watch', N'Samsung Galaxy Watch', 1500),
    (N'Garmin', N'Garmin', 2000),
    (N'Huawei Watch', N'Huawei Watch', 1000),
    (N'Xiaomi band', N'Xiaomi Band', 200),
    (N'Honor band', N'Honor Band', 200),
    (N'Fitbit', N'Fitbit', 800),

    -- ===== Cameras =====
    (N'Canon camera', N'Canon camera', 2000),
    (N'Canon EOS', N'Canon EOS', 3000),
    (N'Sony camera', N'Sony camera', 3000),
    (N'Sony Alpha', N'Sony Alpha', 5000),
    (N'Nikon', N'Nikon camera', 3000),
    (N'GoPro', N'GoPro', 1500),
    (N'DJI Osmo', N'DJI Osmo', 1500),
    (N'DJI', N'DJI', 2000),
    (N'Dash cam', N'داش كام', 300),
    (N'Camera lens Canon', N'Canon lens', 1000),
    (N'Camera lens Sony', N'Sony lens', 1500),

    -- ===== Clothing (global brands in EG) =====
    (N'Nike men', N'Nike رجالي', 150),
    (N'Adidas men', N'Adidas رجالي', 150),
    (N'Puma men', N'Puma رجالي', 120),
    (N'Levi''s men', N'Levi''s رجالي', 150),
    (N'Tommy men', N'Tommy Hilfiger رجالي', 200),
    (N'Calvin Klein men', N'Calvin Klein رجالي', 200),
    (N'Lacoste men', N'Lacoste رجالي', 200),
    (N'Guess men', N'Guess رجالي', 200),
    (N'Under Armour men', N'Under Armour رجالي', 150),
    (N'Reebok men', N'Reebok رجالي', 120),
    (N'Jack Jones', N'Jack Jones', 150),
    (N'Polo Ralph', N'Ralph Lauren', 250),
    (N'Nike women', N'Nike حريمي', 150),
    (N'Adidas women', N'Adidas حريمي', 150),
    (N'Puma women', N'Puma حريمي', 120),
    (N'Levi''s women', N'Levi''s حريمي', 150),
    (N'Guess women', N'Guess حريمي', 200),
    (N'Calvin Klein women', N'Calvin Klein حريمي', 200),
    (N'Tommy women', N'Tommy Hilfiger حريمي', 200),
    (N'Only', N'Only', 120),
    (N'Vero Moda', N'Vero Moda', 120),
    (N'Nike kids', N'Nike أطفال', 100),
    (N'Adidas kids', N'Adidas أطفال', 100),
    (N'Puma kids', N'Puma أطفال', 100),
    (N'Baby clothes', N'ملابس أطفال', 50),

    -- ===== Shoes =====
    (N'Nike shoes', N'Nike أحذية', 250),
    (N'Adidas shoes', N'Adidas أحذية', 250),
    (N'Puma shoes', N'Puma أحذية', 200),
    (N'Reebok shoes', N'Reebok أحذية', 200),
    (N'New Balance', N'New Balance', 300),
    (N'Skechers', N'Skechers', 250),
    (N'Converse', N'Converse', 250),
    (N'Vans', N'Vans', 250),
    (N'Fila shoes', N'Fila أحذية', 200),
    (N'Football Nike', N'Nike كورة', 200),
    (N'Football Adidas', N'Adidas كورة', 200),
    (N'Formal shoes', N'حذاء رسمي', 200),
    (N'Boots', N'بوت', 250),
    (N'Sandals', N'صندل', 100),

    -- ===== Accessories =====
    (N'Nike backpack', N'Nike شنطة', 150),
    (N'Adidas backpack', N'Adidas شنطة', 150),
    (N'Samsonite', N'Samsonite', 400),
    (N'American Tourister', N'American Tourister', 300),
    (N'Wallet', N'محفظة رجالي', 80),
    (N'Belt', N'حزام رجالي', 80),
    (N'Ray-Ban', N'Ray-Ban', 500),
    (N'Fossil watch', N'Fossil', 500),
    (N'Casio watch', N'Casio', 200),
    (N'Seiko', N'Seiko', 800),
    (N'Citizen', N'Citizen', 800),
    (N'Jewelry', N'إكسسوارات', 50),

    -- ===== Beauty =====
    (N'Perfume', N'عطر', 150),
    (N'Hair dryer Philips', N'Philips مجفف شعر', 200),
    (N'Hair dryer Remington', N'Remington مجفف', 200),
    (N'Hair straightener', N'مكواة شعر', 150),
    (N'Hair curler', N'لفاف شعر', 150),
    (N'Shaver Philips', N'Philips ماكينة حلاقة', 200),
    (N'Shaver Braun', N'Braun حلاقة', 250),
    (N'Beard trimmer', N'ماكينة لحية', 150),
    (N'Oral-B', N'Oral-B', 200),
    (N'Skincare device', N'جهاز عناية بشرة', 200),

    -- ===== Baby =====
    (N'Stroller', N'عربة أطفال', 500),
    (N'Car seat', N'كرسي سيارة أطفال', 500),
    (N'Baby monitor', N'بيبي مونيتور', 300),
    (N'Sterilizer', N'معقم رضاعات', 200),
    (N'Breast pump', N'شفط حليب', 300),

    -- ===== Sports =====
    (N'Treadmill', N'مشاية', 2000),
    (N'Exercise bike', N'عجلة رياضية', 1000),
    (N'Dumbbells', N'دمبل', 150),
    (N'Bench', N'بنش حديد', 500),
    (N'Smart scale', N'ميزان ذكي', 150),
    (N'Massage gun', N'مسدس مساج', 200),

    -- ===== Travel =====
    (N'Suitcase Samsonite', N'Samsonite شنطة سفر', 500),
    (N'Suitcase American Tourister', N'American Tourister سفر', 400),
    (N'Travel backpack', N'شنطة سفر', 200),
    (N'Camping', N'Camping', 150),

    -- ===== Watches =====
    (N'Casio', N'Casio', 150),
    (N'Fossil', N'Fossil', 400),
    (N'Seiko watch', N'Seiko', 600),
    (N'Citizen watch', N'Citizen', 600),
    (N'Garmin watch', N'Garmin watch', 1500)
    ) AS v(Name, Query, MinPrice)
)
INSERT INTO dbo.ScraperSearches (
    Name,
    Source,
    Domain,
    Query,
    Locale,
    StartPage,
    Parse,
    ForceHeaders,
    ForceCookies,
    HcPolicy,
    CategoryId,
    MerchantId,
    CheckEmptyGeo,
    SafeSearch,
    Currency,
    SortBy,
    Refinements,
    MinPrice,
    MaxPrice,
    GeoLocation,
    IntervalSeconds,
    IsEnabled,
    LastRunAt,
    LastRunError,
    CreatedAt
)
SELECT
    s.Name,
    N'amazon_search',
    N'eg',
    s.Query,
    N'ar-EG',
    1,              -- StartPage
    1,              -- Parse
    0,              -- ForceHeaders
    0,              -- ForceCookies
    1,              -- HcPolicy
    NULL,           -- CategoryId
    NULL,           -- MerchantId
    NULL,           -- CheckEmptyGeo
    1,              -- SafeSearch
    N'EGP',
    N'featured',
    NULL,           -- Refinements
    s.MinPrice,
    NULL,           -- MaxPrice
    N'Cairo',
    900,            -- IntervalSeconds
    0,              -- IsEnabled (disabled)
    NULL,
    NULL,
    @CreatedAt
FROM Src s
WHERE NOT EXISTS (
    SELECT 1
    FROM dbo.ScraperSearches x
    WHERE x.Name = s.Name
);

SELECT @@ROWCOUNT AS InsertedRows;
